// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://totsuki.harvey-l.com:7000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Organization
 */
export type Organization = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Logo Url
     */
    logo_url?: string | null;
};

/**
 * OrganizationCreate
 */
export type OrganizationCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url?: string;
    /**
     * Logo Url
     */
    logo_url?: string | null;
};

/**
 * OrganizationUpdate
 */
export type OrganizationUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Logo Url
     */
    logo_url?: string | null;
};

/**
 * Person
 */
export type Person = {
    /**
     * Name
     */
    name: string;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Id
     */
    id: string;
    organization: Organization;
};

/**
 * PersonCreate
 */
export type PersonCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Organization
     */
    organization: string;
    /**
     * Role
     */
    role?: string | null;
};

/**
 * PersonUpdate
 */
export type PersonUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Organization
     */
    organization?: string | null;
    /**
     * Role
     */
    role?: string | null;
};

/**
 * Proposition
 */
export type Proposition = {
    /**
     * Id
     */
    id: number;
    speaker: Person;
    /**
     * Statement
     */
    statement: string;
    /**
     * Verifyat
     */
    verifyAt: string;
    video: Video;
};

/**
 * PropositionCreate
 */
export type PropositionCreate = {
    /**
     * Speaker Id
     */
    speaker_id: string;
    /**
     * Statement
     */
    statement: string;
    /**
     * Verify At
     */
    verify_at: string;
    /**
     * Video Id
     */
    video_id: string;
};

/**
 * PropositionUpdate
 */
export type PropositionUpdate = {
    /**
     * Speaker Id
     */
    speaker_id?: string | null;
    /**
     * Statement
     */
    statement?: string | null;
    /**
     * Verify At
     */
    verify_at?: string | null;
    /**
     * Video Id
     */
    video_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Video
 */
export type Video = {
    /**
     * Video Id
     */
    video_id: string;
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Video Url
     */
    video_url: string;
    /**
     * Time
     */
    time: string;
};

/**
 * VideoCreate
 */
export type VideoCreate = {
    /**
     * Video Id
     */
    video_id: string;
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Video Url
     */
    video_url: string;
    /**
     * Time
     */
    time: string;
};

/**
 * VideoUpdate
 */
export type VideoUpdate = {
    /**
     * Video Path
     */
    video_path?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Video Url
     */
    video_url?: string | null;
    /**
     * Time
     */
    time?: string | null;
};

export type ListOrganizationsOrganizationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type ListOrganizationsOrganizationsGetResponses = {
    /**
     * Response List Organizations Organizations Get
     *
     * Successful Response
     */
    200: Array<Organization>;
};

export type ListOrganizationsOrganizationsGetResponse = ListOrganizationsOrganizationsGetResponses[keyof ListOrganizationsOrganizationsGetResponses];

export type CreateOrganizationOrganizationsPostData = {
    body: OrganizationCreate;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type CreateOrganizationOrganizationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrganizationOrganizationsPostError = CreateOrganizationOrganizationsPostErrors[keyof CreateOrganizationOrganizationsPostErrors];

export type CreateOrganizationOrganizationsPostResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type CreateOrganizationOrganizationsPostResponse = CreateOrganizationOrganizationsPostResponses[keyof CreateOrganizationOrganizationsPostResponses];

export type DeleteOrganizationOrganizationsOrgIdDeleteData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}';
};

export type DeleteOrganizationOrganizationsOrgIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOrganizationOrganizationsOrgIdDeleteError = DeleteOrganizationOrganizationsOrgIdDeleteErrors[keyof DeleteOrganizationOrganizationsOrgIdDeleteErrors];

export type DeleteOrganizationOrganizationsOrgIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetOrganizationOrganizationsOrgIdGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}';
};

export type GetOrganizationOrganizationsOrgIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizationOrganizationsOrgIdGetError = GetOrganizationOrganizationsOrgIdGetErrors[keyof GetOrganizationOrganizationsOrgIdGetErrors];

export type GetOrganizationOrganizationsOrgIdGetResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type GetOrganizationOrganizationsOrgIdGetResponse = GetOrganizationOrganizationsOrgIdGetResponses[keyof GetOrganizationOrganizationsOrgIdGetResponses];

export type UpdateOrganizationOrganizationsOrgIdPutData = {
    body: OrganizationUpdate;
    path: {
        /**
         * Org Id
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}';
};

export type UpdateOrganizationOrganizationsOrgIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrganizationOrganizationsOrgIdPutError = UpdateOrganizationOrganizationsOrgIdPutErrors[keyof UpdateOrganizationOrganizationsOrgIdPutErrors];

export type UpdateOrganizationOrganizationsOrgIdPutResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type UpdateOrganizationOrganizationsOrgIdPutResponse = UpdateOrganizationOrganizationsOrgIdPutResponses[keyof UpdateOrganizationOrganizationsOrgIdPutResponses];

export type ListPeoplePeopleGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/people';
};

export type ListPeoplePeopleGetResponses = {
    /**
     * Response List People People Get
     *
     * Successful Response
     */
    200: Array<Person>;
};

export type ListPeoplePeopleGetResponse = ListPeoplePeopleGetResponses[keyof ListPeoplePeopleGetResponses];

export type CreatePersonPeoplePostData = {
    body: PersonCreate;
    path?: never;
    query?: never;
    url: '/people';
};

export type CreatePersonPeoplePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePersonPeoplePostError = CreatePersonPeoplePostErrors[keyof CreatePersonPeoplePostErrors];

export type CreatePersonPeoplePostResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type CreatePersonPeoplePostResponse = CreatePersonPeoplePostResponses[keyof CreatePersonPeoplePostResponses];

export type SearchPeoplePeopleSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Search query (name, position, or org)
         */
        q: string;
        /**
         * Top K
         *
         * Number of results
         */
        top_k?: number;
    };
    url: '/people/search';
};

export type SearchPeoplePeopleSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchPeoplePeopleSearchGetError = SearchPeoplePeopleSearchGetErrors[keyof SearchPeoplePeopleSearchGetErrors];

export type SearchPeoplePeopleSearchGetResponses = {
    /**
     * Response Search People People Search Get
     *
     * Successful Response
     */
    200: Array<Person>;
};

export type SearchPeoplePeopleSearchGetResponse = SearchPeoplePeopleSearchGetResponses[keyof SearchPeoplePeopleSearchGetResponses];

export type DeletePersonPeoplePersonIdDeleteData = {
    body?: never;
    path: {
        /**
         * Person Id
         */
        person_id: string;
    };
    query?: never;
    url: '/people/{person_id}';
};

export type DeletePersonPeoplePersonIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePersonPeoplePersonIdDeleteError = DeletePersonPeoplePersonIdDeleteErrors[keyof DeletePersonPeoplePersonIdDeleteErrors];

export type DeletePersonPeoplePersonIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPersonPeoplePersonIdGetData = {
    body?: never;
    path: {
        /**
         * Person Id
         */
        person_id: string;
    };
    query?: never;
    url: '/people/{person_id}';
};

export type GetPersonPeoplePersonIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPersonPeoplePersonIdGetError = GetPersonPeoplePersonIdGetErrors[keyof GetPersonPeoplePersonIdGetErrors];

export type GetPersonPeoplePersonIdGetResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type GetPersonPeoplePersonIdGetResponse = GetPersonPeoplePersonIdGetResponses[keyof GetPersonPeoplePersonIdGetResponses];

export type UpdatePersonPeoplePersonIdPutData = {
    body: PersonUpdate;
    path: {
        /**
         * Person Id
         */
        person_id: string;
    };
    query?: never;
    url: '/people/{person_id}';
};

export type UpdatePersonPeoplePersonIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePersonPeoplePersonIdPutError = UpdatePersonPeoplePersonIdPutErrors[keyof UpdatePersonPeoplePersonIdPutErrors];

export type UpdatePersonPeoplePersonIdPutResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type UpdatePersonPeoplePersonIdPutResponse = UpdatePersonPeoplePersonIdPutResponses[keyof UpdatePersonPeoplePersonIdPutResponses];

export type ListVideosVideosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/videos';
};

export type ListVideosVideosGetResponses = {
    /**
     * Response List Videos Videos Get
     *
     * Successful Response
     */
    200: Array<Video>;
};

export type ListVideosVideosGetResponse = ListVideosVideosGetResponses[keyof ListVideosVideosGetResponses];

export type CreateVideoVideosPostData = {
    body: VideoCreate;
    path?: never;
    query?: never;
    url: '/videos';
};

export type CreateVideoVideosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVideoVideosPostError = CreateVideoVideosPostErrors[keyof CreateVideoVideosPostErrors];

export type CreateVideoVideosPostResponses = {
    /**
     * Successful Response
     */
    200: Video;
};

export type CreateVideoVideosPostResponse = CreateVideoVideosPostResponses[keyof CreateVideoVideosPostResponses];

export type DeleteVideoVideosVideoIdDeleteData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/videos/{video_id}';
};

export type DeleteVideoVideosVideoIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVideoVideosVideoIdDeleteError = DeleteVideoVideosVideoIdDeleteErrors[keyof DeleteVideoVideosVideoIdDeleteErrors];

export type DeleteVideoVideosVideoIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVideoVideosVideoIdGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/videos/{video_id}';
};

export type GetVideoVideosVideoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoVideosVideoIdGetError = GetVideoVideosVideoIdGetErrors[keyof GetVideoVideosVideoIdGetErrors];

export type GetVideoVideosVideoIdGetResponses = {
    /**
     * Successful Response
     */
    200: Video;
};

export type GetVideoVideosVideoIdGetResponse = GetVideoVideosVideoIdGetResponses[keyof GetVideoVideosVideoIdGetResponses];

export type UpdateVideoVideosVideoIdPutData = {
    body: VideoUpdate;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/videos/{video_id}';
};

export type UpdateVideoVideosVideoIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVideoVideosVideoIdPutError = UpdateVideoVideosVideoIdPutErrors[keyof UpdateVideoVideosVideoIdPutErrors];

export type UpdateVideoVideosVideoIdPutResponses = {
    /**
     * Successful Response
     */
    200: Video;
};

export type UpdateVideoVideosVideoIdPutResponse = UpdateVideoVideosVideoIdPutResponses[keyof UpdateVideoVideosVideoIdPutResponses];

export type ListPropositionsPropositionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/propositions';
};

export type ListPropositionsPropositionsGetResponses = {
    /**
     * Response List Propositions Propositions Get
     *
     * Successful Response
     */
    200: Array<Proposition>;
};

export type ListPropositionsPropositionsGetResponse = ListPropositionsPropositionsGetResponses[keyof ListPropositionsPropositionsGetResponses];

export type CreatePropositionPropositionsPostData = {
    body: PropositionCreate;
    path?: never;
    query?: never;
    url: '/propositions';
};

export type CreatePropositionPropositionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePropositionPropositionsPostError = CreatePropositionPropositionsPostErrors[keyof CreatePropositionPropositionsPostErrors];

export type CreatePropositionPropositionsPostResponses = {
    /**
     * Successful Response
     */
    200: Proposition;
};

export type CreatePropositionPropositionsPostResponse = CreatePropositionPropositionsPostResponses[keyof CreatePropositionPropositionsPostResponses];

export type DeletePropositionPropositionsPropIdDeleteData = {
    body?: never;
    path: {
        /**
         * Prop Id
         */
        prop_id: number;
    };
    query?: never;
    url: '/propositions/{prop_id}';
};

export type DeletePropositionPropositionsPropIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePropositionPropositionsPropIdDeleteError = DeletePropositionPropositionsPropIdDeleteErrors[keyof DeletePropositionPropositionsPropIdDeleteErrors];

export type DeletePropositionPropositionsPropIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPropositionPropositionsPropIdGetData = {
    body?: never;
    path: {
        /**
         * Prop Id
         */
        prop_id: number;
    };
    query?: never;
    url: '/propositions/{prop_id}';
};

export type GetPropositionPropositionsPropIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropositionPropositionsPropIdGetError = GetPropositionPropositionsPropIdGetErrors[keyof GetPropositionPropositionsPropIdGetErrors];

export type GetPropositionPropositionsPropIdGetResponses = {
    /**
     * Successful Response
     */
    200: Proposition;
};

export type GetPropositionPropositionsPropIdGetResponse = GetPropositionPropositionsPropIdGetResponses[keyof GetPropositionPropositionsPropIdGetResponses];

export type UpdatePropositionPropositionsPropIdPutData = {
    body: PropositionUpdate;
    path: {
        /**
         * Prop Id
         */
        prop_id: number;
    };
    query?: never;
    url: '/propositions/{prop_id}';
};

export type UpdatePropositionPropositionsPropIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePropositionPropositionsPropIdPutError = UpdatePropositionPropositionsPropIdPutErrors[keyof UpdatePropositionPropositionsPropIdPutErrors];

export type UpdatePropositionPropositionsPropIdPutResponses = {
    /**
     * Successful Response
     */
    200: Proposition;
};

export type UpdatePropositionPropositionsPropIdPutResponse = UpdatePropositionPropositionsPropIdPutResponses[keyof UpdatePropositionPropositionsPropIdPutResponses];

export type GetPropositionsByPersonPeoplePersonIdPropositionsGetData = {
    body?: never;
    path: {
        /**
         * Person Id
         */
        person_id: string;
    };
    query?: never;
    url: '/people/{person_id}/propositions';
};

export type GetPropositionsByPersonPeoplePersonIdPropositionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropositionsByPersonPeoplePersonIdPropositionsGetError = GetPropositionsByPersonPeoplePersonIdPropositionsGetErrors[keyof GetPropositionsByPersonPeoplePersonIdPropositionsGetErrors];

export type GetPropositionsByPersonPeoplePersonIdPropositionsGetResponses = {
    /**
     * Response Get Propositions By Person People  Person Id  Propositions Get
     *
     * Successful Response
     */
    200: Array<Proposition>;
};

export type GetPropositionsByPersonPeoplePersonIdPropositionsGetResponse = GetPropositionsByPersonPeoplePersonIdPropositionsGetResponses[keyof GetPropositionsByPersonPeoplePersonIdPropositionsGetResponses];
